-- MySQL Script generated by MySQL Workbench
-- 10/05/15 09:45:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipogasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipogasto` (
  `idTipoGasto` INT(6) NOT NULL COMMENT '',
  `nombreTipoGasto` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipoGasto`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_Usuario` INT(7) NOT NULL COMMENT '',
  `nombreUsuario` VARCHAR(255) NOT NULL COMMENT '',
  `cedula` VARCHAR(15) NOT NULL COMMENT '',
  `cargo` VARCHAR(255) NOT NULL COMMENT '',
  `ocupacion` VARCHAR(255) NOT NULL COMMENT '',
  `numeroConctacto` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id_Usuario`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `idProveedor` INT(10) NOT NULL COMMENT '',
  `nombreProveedor` VARCHAR(255) NOT NULL COMMENT '',
  `codigoProveedor` VARCHAR(255) NOT NULL COMMENT '',
  `numeroContacto` VARCHAR(20) NOT NULL COMMENT '',
  `direccion` VARCHAR(120) NOT NULL COMMENT '',
  `nit/cc` VARCHAR(25) NOT NULL COMMENT '',
  `idUsuario` INT(7) NOT NULL COMMENT '',
  `id_registro_contable_gastos` BIGINT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idProveedor`)  COMMENT '',
  CONSTRAINT `proveedor_ibfk_1`
    FOREIGN KEY (`id_registro_contable_gastos`)
    REFERENCES `mydb`.`registrocontablegastos` (`idRegistroContable`),
  CONSTRAINT `proveedor_ibfk_2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`id_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`registrocontablegastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registrocontablegastos` (
  `fecha` DATE NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  `valor` DOUBLE(50,20) NOT NULL COMMENT '',
  `idRegistroContable` BIGINT(20) NOT NULL COMMENT '',
  `idCuentaPUC` INT(10) NOT NULL COMMENT '',
  `idProveedor` INT(10) NULL COMMENT '',
  `idUsuario` INT(7) NOT NULL COMMENT '',
  PRIMARY KEY (`idRegistroContable`)  COMMENT '',
  CONSTRAINT `registrocontablegastos_ibfk_1`
    FOREIGN KEY (`idCuentaPUC`)
    REFERENCES `mydb`.`cuentapuc` (`idCuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `registrocontablegastos_ibfk_2`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `mydb`.`proveedor` (`idProveedor`),
  CONSTRAINT `registrocontablegastos_ibfk_3`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`id_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`cuentapuc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuentapuc` (
  `idCuenta` INT(10) NOT NULL COMMENT '',
  `nombreCuenta` VARCHAR(255) NOT NULL COMMENT '',
  `codigoCuenta` VARCHAR(255) NOT NULL COMMENT '',
  `cuentaPadre` INT(10) NOT NULL COMMENT '',
  `idTipoGasto` INT(6) NOT NULL COMMENT '',
  `id_registro_contable_gasto` BIGINT(20) NOT NULL COMMENT '',
  `idUsuario` INT(7) NOT NULL COMMENT '',
  PRIMARY KEY (`idCuenta`)  COMMENT '',
  CONSTRAINT `cuentapuc_ibfk_1`
    FOREIGN KEY (`idTipoGasto`)
    REFERENCES `mydb`.`tipogasto` (`idTipoGasto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cuentapuc_ibfk_2`
    FOREIGN KEY (`id_registro_contable_gasto`)
    REFERENCES `mydb`.`registrocontablegastos` (`idRegistroContable`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cuentapuc_ibfk_3`
    FOREIGN KEY (`cuentaPadre`)
    REFERENCES `mydb`.`cuentapuc` (`idCuenta`),
  CONSTRAINT `cuentapuc_ibfk_4`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`id_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `idProductos` INT(10) NOT NULL COMMENT '',
  `nombreProducto` VARCHAR(255) NOT NULL COMMENT '',
  `costo` DOUBLE(50,30) NOT NULL COMMENT '',
  `idUsuario` INT(7) NOT NULL COMMENT '',
  `idFrente_Aprovechamientos` INT(10) NOT NULL COMMENT '',
  PRIMARY KEY (`idProductos`)  COMMENT '',
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`id_Usuario`),
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`idFrente_Aprovechamientos`)
    REFERENCES `mydb`.`frenteaprovechamiento` (`idfrenteAprovechamiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`frenteaprovechamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`frenteaprovechamiento` (
  `idfrenteAprovechamiento` INT(10) NOT NULL COMMENT '',
  `nombreFrenteAprovechamiento` VARCHAR(255) NOT NULL COMMENT '',
  `idUsuario` INT(7) NOT NULL COMMENT '',
  `idProductos` INT(10) NOT NULL COMMENT '',
  PRIMARY KEY (`idfrenteAprovechamiento`)  COMMENT '',
  CONSTRAINT `frenteaprovechamiento_ibfk_1`
    FOREIGN KEY (`idProductos`)
    REFERENCES `mydb`.`productos` (`idProductos`),
  CONSTRAINT `frenteaprovechamiento_ibfk_2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`id_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
