-- MySQL Script generated by MySQL Workbench
-- 10/06/15 10:17:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreUsuario` VARCHAR(255) NULL COMMENT '',
  `cedula` VARCHAR(45) NULL COMMENT '',
  `cargo` VARCHAR(255) NULL COMMENT '',
  `ocupacion` VARCHAR(255) NULL COMMENT '',
  `numeroContacto` VARCHAR(45) NULL COMMENT '',
  `RegistroContableGastos_idRegistroContableGastos` BIGINT(25) NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`, `RegistroContableGastos_idRegistroContableGastos`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoGasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoGasto` (
  `idTipoGasto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreTipoGasto` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`idTipoGasto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CuentaPuc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CuentaPuc` (
  `idCuentaPuc` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreCuenta` VARCHAR(255) NULL COMMENT '',
  `codigoCuenta` VARCHAR(255) NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `TipoGasto_idTipoGasto` INT NOT NULL COMMENT '',
  `cuentaPadre` BIGINT(20) NULL COMMENT '',
  PRIMARY KEY (`idCuentaPuc`, `Usuario_idUsuario`, `TipoGasto_idTipoGasto`)  COMMENT '',
  INDEX `fk_CuentaPuc_Usuario1_idx` (`Usuario_idUsuario` ASC)  COMMENT '',
  INDEX `fk_CuentaPuc_TipoGasto1_idx` (`TipoGasto_idTipoGasto` ASC)  COMMENT '',
  INDEX `cuentaPadre_idx` (`idCuentaPuc` ASC, `cuentaPadre` ASC)  COMMENT '',
  CONSTRAINT `fk_CuentaPuc_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CuentaPuc_TipoGasto1`
    FOREIGN KEY (`TipoGasto_idTipoGasto`)
    REFERENCES `mydb`.`TipoGasto` (`idTipoGasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuentaPadre`
    FOREIGN KEY (`idCuentaPuc` , `cuentaPadre`)
    REFERENCES `mydb`.`CuentaPuc` (`cuentaPadre` , `idCuentaPuc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegistroContableGastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RegistroContableGastos` (
  `idRegistroContableGastos` BIGINT(25) NOT NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `valor` DOUBLE NULL COMMENT '',
  `descripcion` LONGTEXT NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `Usuario_RegistroContableGastos_idRegistroContableGastos` BIGINT(25) NOT NULL COMMENT '',
  PRIMARY KEY (`idRegistroContableGastos`, `Usuario_idUsuario`, `Usuario_RegistroContableGastos_idRegistroContableGastos`)  COMMENT '',
  INDEX `fk_RegistroContableGastos_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_RegistroContableGastos_idRegistroContableGastos` ASC)  COMMENT '',
  CONSTRAINT `fk_RegistroContableGastos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_RegistroContableGastos_idRegistroContableGastos`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `RegistroContableGastos_idRegistroContableGastos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CuentaPuc_has_RegistroContableGastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CuentaPuc_has_RegistroContableGastos` (
  `CuentaPuc_idCuentaPuc` BIGINT(20) NOT NULL COMMENT '',
  `RegistroContableGastos_idRegistroContableGastos` BIGINT(25) NOT NULL COMMENT '',
  PRIMARY KEY (`CuentaPuc_idCuentaPuc`, `RegistroContableGastos_idRegistroContableGastos`)  COMMENT '',
  INDEX `fk_CuentaPuc_has_RegistroContableGastos_RegistroContableGas_idx` (`RegistroContableGastos_idRegistroContableGastos` ASC)  COMMENT '',
  INDEX `fk_CuentaPuc_has_RegistroContableGastos_CuentaPuc_idx` (`CuentaPuc_idCuentaPuc` ASC)  COMMENT '',
  CONSTRAINT `fk_CuentaPuc_has_RegistroContableGastos_CuentaPuc`
    FOREIGN KEY (`CuentaPuc_idCuentaPuc`)
    REFERENCES `mydb`.`CuentaPuc` (`idCuentaPuc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CuentaPuc_has_RegistroContableGastos_RegistroContableGastos1`
    FOREIGN KEY (`RegistroContableGastos_idRegistroContableGastos`)
    REFERENCES `mydb`.`RegistroContableGastos` (`idRegistroContableGastos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreProveedor` VARCHAR(255) NULL COMMENT '',
  `codigoProveedor` VARCHAR(255) NULL COMMENT '',
  `numeroContacto` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(255) NULL COMMENT '',
  `Nit/CC` VARCHAR(255) NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `Usuario_RegistroContableGastos_idRegistroContableGastos` BIGINT(25) NOT NULL COMMENT '',
  PRIMARY KEY (`idProveedor`, `Usuario_idUsuario`, `Usuario_RegistroContableGastos_idRegistroContableGastos`)  COMMENT '',
  INDEX `fk_Proveedor_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_RegistroContableGastos_idRegistroContableGastos` ASC)  COMMENT '',
  CONSTRAINT `fk_Proveedor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_RegistroContableGastos_idRegistroContableGastos`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `RegistroContableGastos_idRegistroContableGastos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegistroContableGastos_has_Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RegistroContableGastos_has_Proveedor` (
  `RegistroContableGastos_idRegistroContableGastos` BIGINT(25) NOT NULL COMMENT '',
  `Proveedor_idProveedor` BIGINT(20) NULL COMMENT '',
  PRIMARY KEY (`RegistroContableGastos_idRegistroContableGastos`, `Proveedor_idProveedor`)  COMMENT '',
  INDEX `fk_RegistroContableGastos_has_Proveedor_Proveedor1_idx` (`Proveedor_idProveedor` ASC)  COMMENT '',
  INDEX `fk_RegistroContableGastos_has_Proveedor_RegistroContableGas_idx` (`RegistroContableGastos_idRegistroContableGastos` ASC)  COMMENT '',
  CONSTRAINT `fk_RegistroContableGastos_has_Proveedor_RegistroContableGastos1`
    FOREIGN KEY (`RegistroContableGastos_idRegistroContableGastos`)
    REFERENCES `mydb`.`RegistroContableGastos` (`idRegistroContableGastos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroContableGastos_has_Proveedor_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FrenteAprovechamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FrenteAprovechamiento` (
  `idFrenteAprovechamiento` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreFA` VARCHAR(255) NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `Usuario_RegistroContableGastos_idRegistroContableGastos` BIGINT(25) NOT NULL COMMENT '',
  PRIMARY KEY (`idFrenteAprovechamiento`, `Usuario_idUsuario`, `Usuario_RegistroContableGastos_idRegistroContableGastos`)  COMMENT '',
  INDEX `fk_FrenteAprovechamiento_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_RegistroContableGastos_idRegistroContableGastos` ASC)  COMMENT '',
  CONSTRAINT `fk_FrenteAprovechamiento_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_RegistroContableGastos_idRegistroContableGastos`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `RegistroContableGastos_idRegistroContableGastos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreProducto` VARCHAR(255) NULL COMMENT '',
  `costoProducto` VARCHAR(255) NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `Usuario_RegistroContableGastos_idRegistroContableGastos` BIGINT(25) NOT NULL COMMENT '',
  PRIMARY KEY (`idProductos`, `Usuario_idUsuario`, `Usuario_RegistroContableGastos_idRegistroContableGastos`)  COMMENT '',
  INDEX `fk_Productos_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_RegistroContableGastos_idRegistroContableGastos` ASC)  COMMENT '',
  CONSTRAINT `fk_Productos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_RegistroContableGastos_idRegistroContableGastos`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `RegistroContableGastos_idRegistroContableGastos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FrenteAprovechamiento_has_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FrenteAprovechamiento_has_Productos` (
  `FrenteAprovechamiento_idFrenteAprovechamiento` BIGINT(20) NOT NULL COMMENT '',
  `Productos_idProductos` BIGINT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`FrenteAprovechamiento_idFrenteAprovechamiento`, `Productos_idProductos`)  COMMENT '',
  INDEX `fk_FrenteAprovechamiento_has_Productos_Productos1_idx` (`Productos_idProductos` ASC)  COMMENT '',
  INDEX `fk_FrenteAprovechamiento_has_Productos_FrenteAprovechamient_idx` (`FrenteAprovechamiento_idFrenteAprovechamiento` ASC)  COMMENT '',
  CONSTRAINT `fk_FrenteAprovechamiento_has_Productos_FrenteAprovechamiento1`
    FOREIGN KEY (`FrenteAprovechamiento_idFrenteAprovechamiento`)
    REFERENCES `mydb`.`FrenteAprovechamiento` (`idFrenteAprovechamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FrenteAprovechamiento_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
